name: Draft Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Version tag to draft release (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create Github Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: "Release ${{ inputs.tag_name }}"
          files: |
            src/main.luau
            docs/api.md
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: false
          draft: true
